In [2]:
# Importazione delle librerie necessarie
import pandas as pd
from geopy.distance import geodesic
import numpy as np

# Creazione del DataFrame con i dati forniti
df = pd.read_csv("data/gps-22-12-2024.csv",
    usecols=[0, 1, 2, 3, 4, 5, 6, 7],
    names=["unixtime", "latitudine", "longitudine", "altitudine", "boh1", "boh2", "precisione_orizzontale", "precisione_verticale"])
df = pd.DataFrame(data)

# Calcolo della distanza orizzontale (in metri) tra punti consecutivi
df['distanza_orizzontale'] = 0.0
for i in range(1, len(df)):
    coord1 = (df.loc[i-1, 'latitudine'], df.loc[i-1, 'longitudine'])
    coord2 = (df.loc[i, 'latitudine'], df.loc[i, 'longitudine'])
    df.loc[i, 'distanza_orizzontale'] = geodesic(coord1, coord2).meters

# Calcolo della distanza verticale (in metri) tra punti consecutivi
df['distanza_verticale'] = df['altitudine'].diff().fillna(0)

# Calcolo del tempo trascorso (in secondi) tra punti consecutivi
df['tempo_trascorso'] = df['unixtime'].diff().fillna(0)

# Calcolo della velocit√† (in metri al secondo)
df['velocita'] = np.sqrt(df['distanza_orizzontale']**2 + df['distanza_verticale']**2) / df['tempo_trascorso']
df['velocita'].replace([np.inf, -np.inf], np.nan, inplace=True)  # Gestione di divisioni per zero

# Visualizzazione del DataFrame aggiornato
df

/tmp/ipykernel_328280/853754367.py:27: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['velocita'].replace([np.inf, -np.inf], np.nan, inplace=True)  # Gestione di divisioni per zero

,unixtime,latitudine,longitudine,altitudine,distanza_orizzontale,distanza_verticale,tempo_trascorso,velocita
0,1.734862e+09,46.504500,12.941492,1493.095403,0.000000,0.000000,0.000,NaN
1,1.734862e+09,46.504469,12.941366,1496.071064,10.266877,2.975661,1.543,6.927675
2,1.734862e+09,46.504388,12.941054,1498.110423,25.584741,2.039359,0.999,25.691581
3,1.734862e+09,46.504319,12.940787,1500.489046,21.882272,2.378623,1.002,21.967240
4,1.734862e+09,46.504284,12.940652,1502.011373,11.068463,1.522327,1.001,11.161501
5,1.734862e+09,46.504234,12.940451,1507.208153,16.398706,5.196780,1.999,8.605524
6,1.734862e+09,46.504174,12.940335,1519.664477,11.124823,12.456324,5.001,3.339522